import_component "ui.kv" as UI

web_block "panel_server" {
    before_each -> {
        print("Incoming request to panel...")
    }

    path("/") -> {
        UI.LoginPage()
    }

    path("/dashboard") -> {
        UI.Dashboard("Admin")
    }

    path("/login") -> {
        print("Login attempt detected.")
        redirect("/dashboard")
    }

    path("/fragment") -> {
        render_fragment()
        `<div>Only this fragment</div>`
    }
}

print("Panel server initialized on port 8080")
